### PR TITLE
fix: use count_links for followers count

### LINKED ISSUE #177: Followers / Followees count maxes out at 5
Followers count maxes out at 5, but list shows all followers as expected

### PR DESCRIPTION
**Pull request by mattyg**
Resolves #177

### CODE REVIEW

File: ui/src/pages/AgentProfile.vue [hunk 1]
```diff
@@ -5,8 +5,8 @@
         :profile="profileWithContext?.profile"
         :joined-timestamp="profileWithContext?.joinedTimestamp"
         :agentPubKey="agentPubKey"
-        :creators-count="creators ? creators.length : 0"
-        :followers-count="followers ? followers.length : 0"
+        :creators-count="creatorsCount ? creatorsCount : 0"
+        :followers-count="followersCount ? followersCount : 0"
```
Comment (jost-s) [inline ui/src/pages/AgentProfile.vue:9]:
```suggestion
        :creators-count="creatorsCount || 0"
        :followers-count="followersCount || 0"
```

**Review by jost-s — APPROVED** [review]
Works!
image
