### PR TITLE
Fix/minor quirks

### LINKED ISSUE #117: Full compatibility with WebKit
Ensure app works identically on WebKit as Chromium / Firefox

**Overview**
- Regexp look-behind not supported (#114)
- Some quasar styling elements render improperly (search input)
- Mew submit button doesn't seem to work

### LINKED ISSUE #147: Collected bugs / quirks identified in internal testing
Please put all the bugs / quirks you've found in internal testing here. 

Screenshots are also appreciated if the description isn't obvious.

### PR DESCRIPTION
**Pull request by mattyg**
Resolves #147 
Resolves #117

**overview**
- only display bio + location if they have content in AgentProfile, ensure each label aligns with proper content
- bump vite, vue, pinia
- add back link to all list pages
- refactor search input to use headlessui-based component, rather than QSelect, to avoid rendering issues in webkit gtk browsers
- fix persistance of notificationsRead store to local storage

### CODE REVIEW

**Review by jost-s — COMMENTED** [review]
Please make the placeholder white for better readability
image

File: ui/src/pages/CashtagMewsFeed.vue [hunk 1]
```diff
@@ -1,6 +1,14 @@
...
   <QPage :style-fn="pageHeightCorrection">
-    <h6 class="q-mb-md">
+    <QBtn flat @click="router.back()">
+      <QIcon
+        name="arrow_right_alt"
+        size="lg"
+        style="transform: rotate(180deg); font-weight: 100"
+      />
+      Back
+    </QBtn>
```
Comment (jost-s) [inline ui/src/pages/CashtagMewsFeed.vue:10]: This lends itself to be made its own component.

**Review by jost-s — CHANGES_REQUESTED** [review]

**Review by jost-s — APPROVED** [review]
Luvly!
